### ISSUE TITLE
readme with steps

### ISSUE THREAD

**Issue by anupamme** [cdg720/emnlp2016#1]
Hello

I have read your emnlp paper on language modeling. I would like to replicate your results.

Can you populate the read me and write the steps how to build the model using this code.

Thanks.

**Comment by cdg720** [comment]
Hi anupamme,

I will have this code ready to use by this weekend. You will need the PTB data, which I cannot provide, to replicate the results in the paper.

Thanks,
DK

**Comment by cdg720** [comment]
Hi anupamme,

If you follow the commands in README.rst, you can train your rerankers (provided that you have the WSJ data). I will retrain wsj models with the code in this repository and upload them later. If you encounter problems, please let me know.

Thanks,
DK
